<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter"/>
    </ItemGroup>
    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Arbiter.Infrastructure.Headers\Arbiter.Infrastructure.Headers.csproj"/>
        <ProjectReference Include="..\..\src\Arbiter.Application\Arbiter.Application.csproj"/>
        <ProjectReference Include="..\..\src\Arbiter.Core\Arbiter.Core.csproj"/>
    </ItemGroup>
</Project>