using Arbiter.Domain.Enums;

namespace Arbiter.Infrastructure.Mappers;

public static class StatusCodeMapper
{
    private static readonly Dictionary<Status, string> ReasonPhrases = new()
    {
        [Status.Continue] = "Continue",
        [Status.SwitchingProtocol] = "Switching Protocol",
        [Status.EarlyHints] = "Early Hints",
        [Status.Ok] = "OK",
        [Status.Created] = "Created",
        [Status.Accepted] = "Accepted",
        [Status.NonAuthoritativeInformation] = "Non-Authoritative Information",
        [Status.NoContent] = "No Content",
        [Status.ResetContent] = "Reset Content",
        [Status.PartialContent] = "Partial Content",
        [Status.MultipleChoice] = "Multiple Choice",
        [Status.MovedPermanently] = "Moved Permanently",
        [Status.Found] = "Found",
        [Status.SeeOther] = "See Other",
        [Status.NotModified] = "Not Modified",
        [Status.UseProxy] = "Use Proxy",
        [Status.TemporaryRedirect] = "Temporary Redirect",
        [Status.PermanentRedirect] = "Permanent Redirect",
        [Status.BadRequest] = "Bad Request",
        [Status.Unauthorized] = "Unauthorized",
        [Status.PaymentRequired] = "Payment Required",
        [Status.Forbidden] = "Forbidden",
        [Status.NotFound] = "Not Found",
        [Status.MethodNotAllowed] = "Method Not Allowed",
        [Status.NotAcceptable] = "Not Acceptable",
        [Status.ProxyAuthenticationRequired] = "Proxy Authentication Required",
        [Status.RequestTimeout] = "Request Timeout",
        [Status.Conflict] = "Conflict",
        [Status.Gone] = "Gone",
        [Status.LengthRequired] = "Length Required",
        [Status.PreconditionFailed] = "Precondition Failed",
        [Status.PayloadTooLarge] = "Payload Too large",
        [Status.UriTooLong] = "URI Too Long",
        [Status.UnsupportedMediaType] = "Unsupported Media Type",
        [Status.RangeNotSatisfiable] = "Range Not Satisfiable",
        [Status.ExpectationFailed] = "Expectation Failed",
        [Status.ImATeapot] = "I'm a teapot",
        [Status.MisdirectedRequest] = "Misdirected Request",
        [Status.UnprocessableEntity] = "Unprocessable Entity",
        [Status.Locked] = "Locked",
        [Status.FailedDependency] = "Failed Dependency",
        [Status.TooEarly] = "Too Early",
        [Status.UpgradeRequired] = "Upgrade Required",
        [Status.PreconditionRequired] = "Precondition Required",
        [Status.TooManyRequests] = "Too Many Requests",
        [Status.RequestHeaderFieldsTooLarge] = "Request Header Fields Too Large",
        [Status.UnavailableForLegalReasons] = "Unavailable For Legal Reasons",
        [Status.InternalServerError] = "Internal Server Error",
        [Status.NotImplemented] = "Not Implemented",
        [Status.BadGateway] = "Bad Gateway",
        [Status.ServiceUnavailable] = "Service Unavailable",
        [Status.GatewayTimeout] = "Gateway Timeout",
        [Status.VersionNotSupported] = "HTTP Version Not Supported",
        [Status.VariantAlsoNegotiates] = "Variant Also Negotiates",
        [Status.InsufficientStorage] = "Insufficient Storage",
        [Status.LoopDetected] = "Loop Detected",
        [Status.NotExtended] = "Not Extended",
        [Status.NetworkAuthenticationRequired] = "Network Authentication Required",
    };

    private static readonly Dictionary<Status, int> Codes = new()
    {
        [Status.Continue] = 100,
        [Status.SwitchingProtocol] = 101,
        [Status.EarlyHints] = 103,
        [Status.Ok] = 200,
        [Status.Created] = 201,
        [Status.Accepted] = 202,
        [Status.NonAuthoritativeInformation] = 203,
        [Status.NoContent] = 204,
        [Status.ResetContent] = 205,
        [Status.PartialContent] = 206,
        [Status.MultipleChoice] = 300,
        [Status.MovedPermanently] = 301,
        [Status.Found] = 302,
        [Status.SeeOther] = 303,
        [Status.NotModified] = 304,
        [Status.UseProxy] = 305,
        [Status.TemporaryRedirect] = 307,
        [Status.PermanentRedirect] = 308,
        [Status.BadRequest] = 400,
        [Status.Unauthorized] = 401,
        [Status.PaymentRequired] = 402,
        [Status.Forbidden] = 403,
        [Status.NotFound] = 404,
        [Status.MethodNotAllowed] = 405,
        [Status.NotAcceptable] = 406,
        [Status.ProxyAuthenticationRequired] = 407,
        [Status.RequestTimeout] = 408,
        [Status.Conflict] = 409,
        [Status.Gone] = 410,
        [Status.LengthRequired] = 411,
        [Status.PreconditionFailed] = 412,
        [Status.PayloadTooLarge] = 413,
        [Status.UriTooLong] = 414,
        [Status.UnsupportedMediaType] = 415,
        [Status.RangeNotSatisfiable] = 416,
        [Status.ExpectationFailed] = 417,
        [Status.ImATeapot] = 418,
        [Status.MisdirectedRequest] = 421,
        [Status.UnprocessableEntity] = 422,
        [Status.Locked] = 423,
        [Status.FailedDependency] = 424,
        [Status.TooEarly] = 425,
        [Status.UpgradeRequired] = 426,
        [Status.PreconditionRequired] = 428,
        [Status.TooManyRequests] = 429,
        [Status.RequestHeaderFieldsTooLarge] = 431,
        [Status.UnavailableForLegalReasons] = 451,
        [Status.InternalServerError] = 500,
        [Status.NotImplemented] = 501,
        [Status.BadGateway] = 502,
        [Status.ServiceUnavailable] = 503,
        [Status.GatewayTimeout] = 504,
        [Status.VersionNotSupported] = 505,
        [Status.VariantAlsoNegotiates] = 506,
        [Status.InsufficientStorage] = 507,
        [Status.LoopDetected] = 508,
        [Status.NotExtended] = 510,
        [Status.NetworkAuthenticationRequired] = 511,
    };

    public static string ToReasonPhrase(Status statusCode)
    {
        return ReasonPhrases[statusCode];
    }

    public static int ToCode(Status statusCode)
    {
        return Codes[statusCode];
    }
}