using Arlirad.Infrastructure.QPack.Models;

namespace Arlirad.Infrastructure.QPack.Common;

public static class QPackConsts
{
    public const int DeltaBaseSignMask = 0b1000_0000;
    public const int IndexedFieldLineMask = 0b1000_0000;
    public const int IndexedDynamicFieldLineMask = 0b1000_0000;
    public const int IndexedStaticFieldLine = 0b1100_0000;
    public const int IndexedFieldLinePostBaseIndex = 0b0001_0000;
    public const int LiteralFieldLineWithNameReference = 0b0100_0000;
    public const int LiteralIntermediaryFieldLineWithNameReference = 0b0110_0000;
    public const int LiteralDynamicFieldLineWithNameReference = 0b0100_0000;
    public const int LiteralStaticFieldLineWithNameReference = 0b0101_0000;
    public const int LiteralFieldLineWithPostBaseNameReference = 0b0000_0000;
    public const int LiteralFieldLineWithLiteralName = 0b0010_0000;
    public const int HuffmanStringMask = 0b1000_0000;

    public const int EncoderInstructionDynamicTableCapacity = 0b0010_0000;
    public const int EncoderInstructionInsertWithNameReference = 0b1000_0000;
    public const int EncoderInstructionInsertWithDynamicNameReference = 0b1000_0000;
    public const int EncoderInstructionInsertWithStaticNameReference = 0b1100_0000;
    public const int EncoderInstructionInsertWithLiteralName = 0b0100_0000;
    public const int EncoderInstructionDuplicate = 0b0000_0000;

    public const int DecoderInstructionSectionAcknowledgement = 0b1000_0000;
    public const int DecoderInstructionStreamCancellation = 0b0100_0000;
    public const int DecoderInstructionInsertCountIncrement = 0b0000_0000;

    public const int EntryAdditionalByteCount = 32;

    public static readonly Dictionary<int, QPackField> StaticTable = new() {
        [0] = new QPackField(":authority"),
        [1] = new QPackField(":path", "/"),
        [2] = new QPackField("age", "0"),
        [3] = new QPackField("content-disposition"),
        [4] = new QPackField("content-length", "0"),
        [5] = new QPackField("cookie"),
        [6] = new QPackField("date"),
        [7] = new QPackField("etag"),
        [8] = new QPackField("if-modified-since"),
        [9] = new QPackField("if-none-match"),
        [10] = new QPackField("last-modified"),
        [11] = new QPackField("link"),
        [12] = new QPackField("location"),
        [13] = new QPackField("referer"),
        [14] = new QPackField("set-cookie"),
        [15] = new QPackField(":method", "CONNECT"),
        [16] = new QPackField(":method", "DELETE"),
        [17] = new QPackField(":method", "GET"),
        [18] = new QPackField(":method", "HEAD"),
        [19] = new QPackField(":method", "OPTIONS"),
        [20] = new QPackField(":method", "POST"),
        [21] = new QPackField(":method", "PUT"),
        [22] = new QPackField(":scheme", "http"),
        [23] = new QPackField(":scheme", "https"),
        [24] = new QPackField(":status", "103"),
        [25] = new QPackField(":status", "200"),
        [26] = new QPackField(":status", "304"),
        [27] = new QPackField(":status", "404"),
        [28] = new QPackField(":status", "503"),
        [29] = new QPackField("accept", "*/*"),
        [30] = new QPackField("accept", "application/dns-message"),
        [31] = new QPackField("accept-encoding", "gzip, deflate, br"),
        [32] = new QPackField("accept-ranges", "bytes"),
        [33] = new QPackField("access-control-allow-headers", "cache-control"),
        [34] = new QPackField("access-control-allow-headers", "content-type"),
        [35] = new QPackField("access-control-allow-origin", "*"),
        [36] = new QPackField("cache-control", "max-age=0"),
        [37] = new QPackField("cache-control", "max-age=2592000"),
        [38] = new QPackField("cache-control", "max-age=604800"),
        [39] = new QPackField("cache-control", "no-cache"),
        [40] = new QPackField("cache-control", "no-store"),
        [41] = new QPackField("cache-control", "public, max-age=31536000"),
        [42] = new QPackField("content-encoding", "br"),
        [43] = new QPackField("content-encoding", "gzip"),
        [44] = new QPackField("content-type", "application/dns-message"),
        [45] = new QPackField("content-type", "application/javascript"),
        [46] = new QPackField("content-type", "application/json"),
        [47] = new QPackField("content-type", "application/x-www-form-urlencoded"),
        [48] = new QPackField("content-type", "image/gif"),
        [49] = new QPackField("content-type", "image/jpeg"),
        [50] = new QPackField("content-type", "image/png"),
        [51] = new QPackField("content-type", "text/css"),
        [52] = new QPackField("content-type", "text/html; charset=utf-8"),
        [53] = new QPackField("content-type", "text/plain"),
        [54] = new QPackField("content-type", "text/plain;charset=utf-8"),
        [55] = new QPackField("range", "bytes=0-"),
        [56] = new QPackField("strict-transport-security", "max-age=31536000"),
        [57] = new QPackField("strict-transport-security", "max-age=31536000; includesubdomains"),
        [58] = new QPackField("strict-transport-security", "max-age=31536000; includesubdomains; preload"),
        [59] = new QPackField("vary", "accept-encoding"),
        [60] = new QPackField("vary", "origin"),
        [61] = new QPackField("x-content-type-options", "nosniff"),
        [62] = new QPackField("x-xss-protection", "1; mode=block"),
        [63] = new QPackField(":status", "100"),
        [64] = new QPackField(":status", "204"),
        [65] = new QPackField(":status", "206"),
        [66] = new QPackField(":status", "302"),
        [67] = new QPackField(":status", "400"),
        [68] = new QPackField(":status", "403"),
        [69] = new QPackField(":status", "421"),
        [70] = new QPackField(":status", "425"),
        [71] = new QPackField(":status", "500"),
        [72] = new QPackField("accept-language"),
        [73] = new QPackField("access-control-allow-credentials", "FALSE"),
        [74] = new QPackField("access-control-allow-credentials", "TRUE"),
        [75] = new QPackField("access-control-allow-headers", "*"),
        [76] = new QPackField("access-control-allow-methods", "get"),
        [77] = new QPackField("access-control-allow-methods", "get, post, options"),
        [78] = new QPackField("access-control-allow-methods", "options"),
        [79] = new QPackField("access-control-expose-headers", "content-length"),
        [80] = new QPackField("access-control-request-headers", "content-type"),
        [81] = new QPackField("access-control-request-method", "get"),
        [82] = new QPackField("access-control-request-method", "post"),
        [83] = new QPackField("alt-svc", "clear"),
        [84] = new QPackField("authorization"),
        [85] = new QPackField("content-security-policy", "script-src 'none'; object-src 'none'; base-uri 'none'"),
        [86] = new QPackField("early-data", "1"),
        [87] = new QPackField("expect-ct"),
        [88] = new QPackField("forwarded"),
        [89] = new QPackField("if-range"),
        [90] = new QPackField("origin"),
        [91] = new QPackField("purpose", "prefetch"),
        [92] = new QPackField("server"),
        [93] = new QPackField("timing-allow-origin", "*"),
        [94] = new QPackField("upgrade-insecure-requests", "1"),
        [95] = new QPackField("user-agent"),
        [96] = new QPackField("x-forwarded-for"),
        [97] = new QPackField("x-frame-options", "deny"),
        [98] = new QPackField("x-frame-options", "sameorigin"),
    };

    public static readonly Dictionary<string, int> StaticNameIndex = new(StringComparer.OrdinalIgnoreCase) {
        [":authority"] = 0,
        [":path"] = 1,
        ["age"] = 2,
        ["content-disposition"] = 3,
        ["content-length"] = 4,
        ["cookie"] = 5,
        ["date"] = 6,
        ["etag"] = 7,
        ["if-modified-since"] = 8,
        ["if-none-match"] = 9,
        ["last-modified"] = 10,
        ["link"] = 11,
        ["location"] = 12,
        ["referer"] = 13,
        ["set-cookie"] = 14,
        [":method"] = 15,
        [":scheme"] = 22,
        [":status"] = 24,
        ["accept"] = 29,
        ["accept-encoding"] = 31,
        ["accept-ranges"] = 32,
        ["access-control-allow-headers"] = 33,
        ["access-control-allow-origin"] = 35,
        ["cache-control"] = 36,
        ["content-encoding"] = 42,
        ["content-type"] = 44,
        ["range"] = 55,
        ["strict-transport-security"] = 56,
        ["vary"] = 59,
        ["x-content-type-options"] = 61,
        ["x-xss-protection"] = 62,
        ["accept-language"] = 72,
        ["access-control-allow-credentials"] = 73,
        ["access-control-allow-methods"] = 76,
        ["access-control-expose-headers"] = 79,
        ["access-control-request-headers"] = 80,
        ["access-control-request-method"] = 81,
        ["alt-svc"] = 83,
        ["authorization"] = 84,
        ["content-security-policy"] = 85,
        ["early-data"] = 86,
        ["expect-ct"] = 87,
        ["forwarded"] = 88,
        ["if-range"] = 89,
        ["origin"] = 90,
        ["purpose"] = 91,
        ["server"] = 92,
        ["timing-allow-origin"] = 93,
        ["upgrade-insecure-requests"] = 94,
        ["user-agent"] = 95,
        ["x-forwarded-for"] = 96,
        ["x-frame-options"] = 97,
    };

    public static readonly Dictionary<(string name, string value), int> StaticExactIndex = new(new ExactMatcher()) {
        [(":path", "/")] = 1,
        [("age", "0")] = 2,
        [("content-length", "0")] = 4,
        [(":method", "CONNECT")] = 15,
        [(":method", "DELETE")] = 16,
        [(":method", "GET")] = 17,
        [(":method", "HEAD")] = 18,
        [(":method", "OPTIONS")] = 19,
        [(":method", "POST")] = 20,
        [(":method", "PUT")] = 21,
        [(":scheme", "http")] = 22,
        [(":scheme", "https")] = 23,
        [(":status", "103")] = 24,
        [(":status", "200")] = 25,
        [(":status", "304")] = 26,
        [(":status", "404")] = 27,
        [(":status", "503")] = 28,
        [("accept", "*/*")] = 29,
        [("accept", "application/dns-message")] = 30,
        [("accept-encoding", "gzip, deflate, br")] = 31,
        [("accept-ranges", "bytes")] = 32,
        [("access-control-allow-headers", "cache-control")] = 33,
        [("access-control-allow-headers", "content-type")] = 34,
        [("access-control-allow-origin", "*")] = 35,
        [("cache-control", "max-age=0")] = 36,
        [("cache-control", "max-age=2592000")] = 37,
        [("cache-control", "max-age=604800")] = 38,
        [("cache-control", "no-cache")] = 39,
        [("cache-control", "no-store")] = 40,
        [("cache-control", "public, max-age=31536000")] = 41,
        [("content-encoding", "br")] = 42,
        [("content-encoding", "gzip")] = 43,
        [("content-type", "application/dns-message")] = 44,
        [("content-type", "application/javascript")] = 45,
        [("content-type", "application/json")] = 46,
        [("content-type", "application/x-www-form-urlencoded")] = 47,
        [("content-type", "image/gif")] = 48,
        [("content-type", "image/jpeg")] = 49,
        [("content-type", "image/png")] = 50,
        [("content-type", "text/css")] = 51,
        [("content-type", "text/html; charset=utf-8")] = 52,
        [("content-type", "text/plain")] = 53,
        [("content-type", "text/plain;charset=utf-8")] = 54,
        [("range", "bytes=0-")] = 55,
        [("strict-transport-security", "max-age=31536000")] = 56,
        [("strict-transport-security", "max-age=31536000; includesubdomains")] = 57,
        [("strict-transport-security", "max-age=31536000; includesubdomains; preload")] = 58,
        [("vary", "accept-encoding")] = 59,
        [("vary", "origin")] = 60,
        [("x-content-type-options", "nosniff")] = 61,
        [("x-xss-protection", "1; mode=block")] = 62,
        [(":status", "100")] = 63,
        [(":status", "204")] = 64,
        [(":status", "206")] = 65,
        [(":status", "302")] = 66,
        [(":status", "400")] = 67,
        [(":status", "403")] = 68,
        [(":status", "421")] = 69,
        [(":status", "425")] = 70,
        [(":status", "500")] = 71,
        [("access-control-allow-credentials", "FALSE")] = 73,
        [("access-control-allow-credentials", "TRUE")] = 74,
        [("access-control-allow-headers", "*")] = 75,
        [("access-control-allow-methods", "get")] = 76,
        [("access-control-allow-methods", "get, post, options")] = 77,
        [("access-control-allow-methods", "options")] = 78,
        [("access-control-expose-headers", "content-length")] = 79,
        [("access-control-request-headers", "content-type")] = 80,
        [("access-control-request-method", "get")] = 81,
        [("access-control-request-method", "post")] = 82,
        [("alt-svc", "clear")] = 83,
        [("content-security-policy", "script-src 'none'; object-src 'none'; base-uri 'none'")] = 85,
        [("early-data", "1")] = 86,
        [("purpose", "prefetch")] = 91,
        [("timing-allow-origin", "*")] = 93,
        [("upgrade-insecure-requests", "1")] = 94,
        [("x-frame-options", "deny")] = 97,
        [("x-frame-options", "sameorigin")] = 98,
    };

    public static bool Is(byte b, int mask, int instruction) => (b & mask) == instruction;
    public static bool Is(int b, int mask, int instruction) => (b & mask) == instruction;

    private class ExactMatcher : IEqualityComparer<(string name, string value)>
    {
        public bool Equals((string name, string value) x, (string name, string value) y) => string.Equals(x.name, y.name, StringComparison.OrdinalIgnoreCase) && string.Equals(x.value, y.value, StringComparison.Ordinal);

        public int GetHashCode((string name, string value) obj) => HashCode.Combine(StringComparer.OrdinalIgnoreCase.GetHashCode(obj.name), obj.value);
    }
}